from __future__ import annotations
from typing import Protocol, Callable, Any, TypeVar

T = TypeVar("T")

class TranslatorProto(Protocol):
    def __call__(self, key: str, **kwargs: Any) -> str:
        ...

class EventDispatcherProto(Protocol):
    def dispatch(self, event_name: str, data: Any = None) -> None:
        ...
    def subscribe(self, event_name: str, callback: Callable[..., Any]) -> None:
        ...
    def unsubscribe(self, event_name: str, callback: Callable[..., Any]) -> None:
        ...

class ThemeManagerProto(Protocol):
    def apply_theme_to_widget_tree(self, widget: Any, theme: dict[str, str]) -> None:
        ...
    def get_current_theme(self) -> str:
        ...

class SettingsManagerProto(Protocol):
    @property
    def settings(self) -> dict[str, Any]:
        ...
    @settings.setter
    def settings(self, val: dict[str, Any]) -> None:
        ...
    def get_setting(self, key: str, default: Any = None) -> Any:
        ...
    def set_setting(self, key: str, value: Any) -> None:
        ...
    def save_settings(self) -> None:
        ...
    def load_settings_from_file(self, filepath: str) -> bool:
        ...
    def save_settings_to_file(self, filepath: str) -> None:
        ...
    def notify_listeners(self) -> None:
        ...
    def _get_default_settings(self) -> dict[str, Any]:
        ...

class GUIContextProto(Protocol):
    @property
    def translator(self) -> TranslatorProto:
        ...
    @property
    def event_dispatcher(self) -> EventDispatcherProto:
        ...
    @property
    def theme_manager(self) -> ThemeManagerProto:
        ...
